version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  db:
    image: postgres:15
    container_name: finsight_postgres
    restart: always
    environment:
        POSTGRES_USER: finsight
        POSTGRES_PASSWORD: password
        POSTGRES_DB: finsightdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
volumes:
  pgdata:
  redis_data: